### ISSUE TITLE
Problem with Jupyter Notebook Memory Limit

### ISSUE THREAD

**Issue by EverardoG** [DexaiRobotics/drake-torch#17]
Jupyter notebooks seem to have a really low memory limit (~156 MB) for me. Setting the `NotebookApp.max_buffer_size=10000000000` command line option doesn't seem to help with that. The full command for my jupyter notebook is 

`jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.max_buffer_size=10000000000 --ResourceUseDisplay.mem_limit=10000000000`

where the `--ResourceUseDisplay.mem_limit` option is for a plugin to display the memory limit. 

There should be some way of fixing this in the drake torch dockerfile. I might try it later, but if someone else can tackle it, that also works. :bug: 

To get jupyter notebooks to display the memory consumption (ie: how I got it to tell me it crashed around 156 MB), I used `python3 -m pip install nbresuse` to get a jupyter notebook plugin to show memory consumption in the top right.

EDIT: I got the memory consumption wrong. I'm going to run the code again and update with the actual memory consumption that jupyter crashed at. - I can't actually get the exact memory consumption it crashed at because it resets the memory to what it was before it crashed and throws away all the data from the cell that caused the memory overflow. It was actually around 10,000 MB when it crashed.

**Comment by duanyutong** [comment]
Thanks for the report and I just noticed it. Do you still have this issue with the latest melodic or noetic images we publish? We haven't seen jupyter crash due to memory limits. Is this a specific problem for our image or a general jupyter problem?
